// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wudgrsitseuilldkmmqv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind1ZGdyc2l0c2V1aWxsZGttbXF2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxNzc4NzgsImV4cCI6MjA3Mzc1Mzg3OH0.drQsEBbojVV7y_PsR0_h4O02l37MECnNDN74GgaHLuE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});